### PR TITLE
Fix for big-endian architectures

### PR DESCRIPTION
**Pull request by rubund**

### CODE REVIEW

**Comment by zecke** [comment]
Dear Rubund,

I have fetched and cherry-picked it but as an old-school project we would still prefer if you send the patch to our mailinglist. Thank you very much for your contribution and if you could send another mail with the plan/status of getting our libraries into debian that would be appreciated.

I am looking for better listing of all copyright holders, ABI checks, etc. :)

thank you

**Comment by rubund** [comment]
Sorry about the pull request. I forgot for a moment that the github repo is just a mirror of the repo on osmocom, and I just wanted to make it easier for you. I also posted one patch on the mailing list that wasn't as nice.

**Comment by arr2036** [comment]
@zecke Which list is best to use?  I did look, but none seemed to related directly to libsccp.

**Comment by zecke** [comment]
> On 17 May 2016, at 21:49, Arran Cudbard-Bell notifications@github.com wrote:
> 
> @zecke Which list is best to use? I did look, but none seemed to related directly to libsccp.

openbsc and if a patch directly push into our new gerrit (http://osmocom.org/projects/cellular-infrastructure/wiki/Gerrit)

**Pull request closed without merging**
